# src/core/exceptions.py

class UserCancelledError(Exception):
    """Excepción lanzada cuando el usuario cancela una operación."""
    pass